# This is a basic workflow that is manually triggered

name: Manual workflow

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:


jobs:
  test:
    strategy:
      matrix:
        environment: [customera, customerb, customerc]
    runs-on: ubuntu-latest
    environment: ${{matrix.environment}}
    steps:
      - name: Display matrix and index
        run: |
          echo "Running on ${{ matrix.os }} with Node.js ${{ matrix.node }}"
          echo "This is matrix job #${{ strategy.job-index }}"
          echo "Environment Var #${{ vars.customer_name }}"
